### ISSUE TITLE
syslog::kernel_target parameter

### ISSUE THREAD

**Issue by philippvh** [ghoneycutt/puppet-module-rsyslog#63]
Hej,

I think, the parameter syslog::kernel_target has the wrong type / intention.

When looking at the template file, the line being parametrized was intended for "log kernel messages to console". For nothing else.
The next line then takes care of "add lots of stuff (including kernel messages >=info level) to /var/log.messages". This line is not parametrized in the module currently.

So, a Boolean like syslog::kernel_to_console for enabling/disabling the console logging line completely would be a good solution.

Allowing a different target destination (restricted to an absolute path) has the following issues:
- With default settings, 2 rules log kernel messages to /var/log/messages. (Rather harmless.)
- When trying to disable kernel messages being written to /var/log/messages, entering "/dev/null" does not help (messages are still logged via the 2nd rule). However, the existence of the parameter gives the impression, that you could switch it off. (Annoying, if somebody hits this case.)
- Dropping messages (with "~" as destination) also does not work, since it's not an absolute path.
- Since syslog::kernel_target is used in the list of files for logrotate, "/dev/console" and/or "/dev/null" could be added to the logrotate configuration. Not to talk about "~", which is at least prevented by the module. :-)

All these issues would not exist, if the parameter was a boolean (preventing misunderstandings with logrotate setup; console logging should be disregarded there completely), and it would be clear to the user, that only the console logging (not the file logging) can be affected here.

Before investing major code-rewrite and incompatible parameter change, I wanted to raise the issue here as discussion point.

**Comment by ghoneycutt** [comment]
Hi @philippvh 

Thanks for asking about this. The kernel target is simply the target for `kern.*` and does not imply anything to do with the console. This module could certainly use more granularity on defining what gets logged where. The ideal approach would be to specify a hash of log levels and targets. What do you think of this, represented in YAML here.

``` yaml
rsyslog::log_entries:
  'kern.*':
    '/var/log/messages'
  '*.info;mail.none;authpriv.none;cron.none':
    '/var/log/messages'
  'authpriv.*':
    '/var/log/secure'
  'mail.*':
    '-/var/log/maillog'
  'cron.*':
    '/var/log/cron'
```

**Comment by Phil-Friderici** [comment]
$kernel_target shouldn't be a problem. You can pass your own list of files to rotate with $logrotate_syslog_files.

**Comment by philippvh** [comment]
Thanks for the quick replies and proposals!

Having the default log section as variable as described above, would definitely solve the issue.
And then add a disclaimer to the documentation, that when changing the list of target files, you should also update $logrotate_syslog_files accordingly.

Also the thing I was working on would be covered by this: I wanted a line like the following, to drop selected kernel messages, which needs to be added before the first line writing kernel messages any place else.
<pre>
:msg, contains, "sctp: Use " ~
</pre>

**Comment by Phil-Friderici** [comment]
@philippvh @ghoneycutt could add this next week...

**Comment by philippvh** [comment]
Potentially stupid question: The hiera/puppet hash works "in sequence"? I.e. when you serialize it into the config file, the sequence of entries will be kept as in the hiera source?
(Sequence of rules has an impact, in case you want to add e.g. a drop rule.)

**Comment by Phil-Friderici** [comment]
@philippvh yes as far as I remember it's in sequence

**Comment by ghoneycutt** [comment]
Aha, you are correct, so the hash would not work, though an array of hashes would

**Comment by Phil-Friderici** [comment]
This should work and keep the sequence:
<pre>
rsyslog::log_entries:
  - 'kern.* /var/log/messages'
  - '*.info;mail.none;authpriv.none;cron.none /var/log/messages'
  - 'authpriv.* /var/log/secure'
  - 'mail.* -/var/log/maillog'
  - 'cron.* /var/log/cron'
</pre>

**Comment by ghoneycutt** [comment]
@Phil-Friderici This is a much simpler solution that I think we should go with. The benefit of using a hash for this would allow us to separate facility and kernel for added validation. The simplicity above is better though.

**Comment by Phil-Friderici** [comment]
@ghoneycutt validation would be nice. Although I see difficulties in validating legal values like ```-/var/log/maillog```

**Comment by Phil-Friderici** [comment]
Should I include the comments in the module default ?
This would avoid changes of rsyslog.conf when upgrading :)

It works so well that I didn't need to change the spec tests for the default settings at all ;)

init.pp extract:
<pre>
  $default_log_entries = [
    '# Log all kernel messages to the console.',
    '# Logging much else clutters up the screen.',
    '#kern.*                                                 /dev/console',
    "kern.*                                                  $kernel_target",
    '',
    '# Log anything (except mail) of level info or higher.',
    '# Don\'t log private authentication messages!',
    '*.info;mail.none;authpriv.none;cron.none                /var/log/messages',
    '',
    '# The authpriv file has restricted access.',
    'authpriv.*                                              /var/log/secure',
    '',
    '# Log all the mail messages in one place.',
    'mail.*                                                  -/var/log/maillog',
    '',
    '# Log cron stuff',
    'cron.*                                                  /var/log/cron',
  ]

  $log_entries_real = $log_entries ? {
    'USE_DEFAULTS' => $default_log_entries,
    default        => $log_entries
  }

  validate_array($log_entries_real)
}
</pre>

**Comment by Phil-Friderici** [comment]
PS: above sample assumes that we want to keep $kernel_target for compatibility reasons.

**Comment by Phil-Friderici** [comment]
seems there is no spec test for $kernel_target

**Comment by Phil-Friderici** [comment]
@philippvh if you dare you can try this. I'll create an rsyslog environment containing this code.

**Comment by philippvh** [comment]
@Phil-Friderici Tested with seaserv134 - works well and as intended.
Just copied the default rules, removed 1, added 1, and result is as expected. :-)

**Comment by Phil-Friderici** [comment]
@philippvh thanks for verifying :+1:

**Comment by ghoneycutt** [comment]
Closing this as we can take the discussion to the actual PR #64
