### ISSUE TITLE
systemd-journald.socket needs to be restarted after imjournal is configured on EL7

### ISSUE THREAD

**Issue by joshuabaird** [ghoneycutt/puppet-module-rsyslog#95]
If imjournal is configured on EL7, ```/dev/log``` needs to be re-created in order for local logging to /var/log to resume.  A restart of the ```systemd-journald.socket``` service will re-create ```/dev/log```.

**Comment by joshuabaird** [comment]
PR #96

**Comment by jyaworski** [comment]
This looks to have been closed by #97 @ghoneycutt

**Comment by ghoneycutt** [comment]
Released in 0.24.0 from PR #97
