### ISSUE TITLE
Future updates

### ISSUE THREAD

**Issue by bortek** [ghoneycutt/puppet-module-rsyslog#98]
Hi

I have a question. I want to use this module in my RHEL7.X environment and plan to update it in the future when there are new releases of this module. But I need to set some parameters like $log_server , $log_server_port or others.

If I just fetch new version of the module and overwrite it it will overwrite my parameters too. 

I would ideally like to have a separate file with my own parameters which is "sourced" by the module. That way I would keep my own params file.

Is this possible?

**Comment by ghoneycutt** [comment]
Hi @bortek 
When using 3rd party modules such as this, you should never have to modify it for normal use, only if you wanted to add extra functionality. You should be putting your data in Hiera. That lets you separate your data from the code for the reasons you mention above.

Here's an example of what that looks like. You would have a yaml file like this and Puppet will automatically look up `class`::`variable` and use that data.

``` yaml
---
rsyslog::log_server:
  - 'log1.example.com'
  - 'log2.example.com'
```

https://docs.puppetlabs.com/hiera/1/puppet.html#automatic-parameter-lookup

**Comment by bortek** [comment]
Thanks ghoneycutt. Exactly what I was looking for.
